
motor_fr_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_right_motor_joint
  pid:
    p: 5.0

motor_fl_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_left_motor_joint
  pid:
    p: 5.0

motor_rr_controller:
 type: velocity_controllers/JointVelocityController
 joint: rear_right_motor_joint
 pid:
   p: 5.0

motor_rl_controller:
 type: velocity_controllers/JointVelocityController
 joint: rear_left_motor_joint
 pid:
   p: 5.0
